/**
 * Parse content/neuroanatomy/sources/umf-exam-affirmations.json
 * + optional umf-exam-affirmations.en.json
 * → mocks/questions_neuro_umf_exam.ts
 *
 * Regenerate source JSON from docx first:
 *   python scripts/parse-neuroanatomie-docx.py
 *
 * Translate RO → EN (resume-safe):
 *   bun run scripts/translate-neuro-umf-exam-en.ts
 *
 * Then:
 *   bun run scripts/build-neuro-umf-exam-questions.ts
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const SOURCE = path.join(ROOT, 'content/neuroanatomy/sources/umf-exam-affirmations.json');
const EN_SOURCE = path.join(ROOT, 'content/neuroanatomy/sources/umf-exam-affirmations.en.json');
const OUT = path.join(ROOT, 'mocks/questions_neuro_umf_exam.ts');

type SourceQuestion = {
  id: string;
  stem: string;
  options: string[];
  correctAnswers: number[];
};

type EnQuestion = {
  id: string;
  stem: string;
  options: string[];
};

function escapeTs(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')
    .replace(/\r\n/g, '\n')
    .replace(/\n/g, '\\n');
}

function loadEnById(): Map<string, EnQuestion> {
  if (!fs.existsSync(EN_SOURCE)) return new Map();
  const entries = JSON.parse(fs.readFileSync(EN_SOURCE, 'utf8')) as EnQuestion[];
  return new Map(entries.map((entry) => [entry.id, entry]));
}

function alignEnOptions(roOptions: string[], enOptions: string[]): string[] {
  const aligned = enOptions.slice(0, roOptions.length);
  while (aligned.length < roOptions.length) {
    aligned.push(roOptions[aligned.length]);
  }
  return aligned;
}

function emitQuestion(question: SourceQuestion, en?: EnQuestion): string {
  const correctAnswers = `[${question.correctAnswers.join(', ')}]`;
  const enStem = en?.stem ?? question.stem;
  const enOptions = alignEnOptions(question.options, en?.options ?? question.options);
  const enOpts = enOptions.map((option) => `\`${escapeTs(option)}\``).join(',\n      ');
  const roOpts = question.options.map((option) => `\`${escapeTs(option)}\``).join(',\n      ');

  return `  {
    id: '${question.id}',
    category: 'neuroanatomy',
    difficulty: 'medium',
    format: 'multiple',
    question: \`${escapeTs(enStem)}\`,
    question_ro: \`${escapeTs(question.stem)}\`,
    options: [
      ${enOpts},
    ],
    options_ro: [
      ${roOpts},
    ],
    correctAnswer: ${question.correctAnswers[0] ?? 0},
    correctAnswers: ${correctAnswers},
    explanation: 'Select all correct affirmations.',
    explanation_ro: 'Selectează toate afirmațiile corecte.',
  }`;
}

function main(): void {
  const raw = fs.readFileSync(SOURCE, 'utf8');
  const questions = JSON.parse(raw) as SourceQuestion[];
  const enById = loadEnById();

  const invalid = questions.filter((question) => !question.correctAnswers.length);
  if (invalid.length) {
    console.warn(`Warning: ${invalid.length} questions have no marked correct answers`);
  }

  const missingEn = questions.filter((question) => !enById.has(question.id)).length;
  if (missingEn) {
    console.warn(`Warning: ${missingEn} questions missing English translation (using Romanian fallback)`);
  }

  const body = questions.map((question) => emitQuestion(question, enById.get(question.id))).join(',\n');
  const output = `import type { Question } from './questions';

/** UMF-style neuroanatomy exam affirmations (multi-select). Generated by scripts/build-neuro-umf-exam-questions.ts */
export const neuroUmfExamQuestions: Question[] = [
${body},
];
`;

  fs.writeFileSync(OUT, output, 'utf8');
  console.log(`Wrote ${OUT} (${questions.length} questions, ${enById.size} with EN)`);
}

main();
