#!/usr/bin/env python3
"""Generate 3 App Store App Previews (6.5\" / 1080×1920, 20s, H.264) from ios-6.5 PNGs."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

# Apple: iPhone 6.5" App Preview portrait — 886×1920, 1080×1920, or 1290×2796
PREVIEW_W, PREVIEW_H = 1080, 1920
FPS = 30
DURATION_SEC = 20

ROOT = Path(__file__).resolve().parent.parent
SCREENSHOTS = ROOT / "docs" / "app-store-screenshots" / "ios-6.5"
OUT = ROOT / "docs" / "app-store-screenshots" / "ios-6.5-previews"

# First three = install-sheet funnel (same order as screenshots README)
PREVIEWS: list[tuple[str, str]] = [
    ("01-medvba.png", "01-medvba.mp4"),
    ("02-your-dashboard.png", "02-your-dashboard.mp4"),
    ("03-practice-quizzes.png", "03-practice-quizzes.mp4"),
]


def build_preview(src: Path, dest: Path) -> None:
    frames = FPS * DURATION_SEC
    # Slow zoom on centered 1080×1920 canvas; short fade-in
    vf = (
        f"scale={PREVIEW_W}:{PREVIEW_H}:force_original_aspect_ratio=decrease,"
        f"pad={PREVIEW_W}:{PREVIEW_H}:(ow-iw)/2:(oh-ih)/2:color=0x0A121E,"
        f"format=yuv420p,"
        f"zoompan=z='min(1+0.00035*on,1.12)':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)'"
        f":d={frames}:s={PREVIEW_W}x{PREVIEW_H}:fps={FPS},"
        f"fade=t=in:st=0:d=0.6"
    )
    cmd = [
        "ffmpeg",
        "-y",
        "-loop",
        "1",
        "-i",
        str(src),
        "-vf",
        vf,
        "-t",
        str(DURATION_SEC),
        "-c:v",
        "libx264",
        "-profile:v",
        "high",
        "-pix_fmt",
        "yuv420p",
        "-movflags",
        "+faststart",
        str(dest),
    ]
    subprocess.run(cmd, check=True, capture_output=True, text=True)


def main() -> None:
    if not shutil.which("ffmpeg"):
        print("ffmpeg not found on PATH", file=sys.stderr)
        sys.exit(1)

    OUT.mkdir(parents=True, exist_ok=True)
    for src_name, out_name in PREVIEWS:
        src = SCREENSHOTS / src_name
        if not src.exists():
            raise FileNotFoundError(f"Missing screenshot (run generate-app-store-screenshots.py): {src}")
        dest = OUT / out_name
        print(f"Rendering {dest.name} ({PREVIEW_W}×{PREVIEW_H}, {DURATION_SEC}s)…")
        build_preview(src, dest)
        print(f"Wrote {dest}")

    readme = ROOT / "docs" / "app-store-screenshots" / "README-app-previews.md"
    readme.write_text(
        "\n".join(
            [
                "# App Store App Previews (6.5\" / 1080×1920)",
                "",
                "Upload up to **3** videos to **App Store Connect → Previews and Screenshots → iPhone 6.5\" Display**",
                "(same slot as screenshots; previews appear before stills).",
                "",
                "| # | File | Screen |",
                "|---|------|--------|",
                "| 1 | `ios-6.5-previews/01-medvba.mp4` | MEDVBA |",
                "| 2 | `ios-6.5-previews/02-your-dashboard.mp4` | Your dashboard |",
                "| 3 | `ios-6.5-previews/03-practice-quizzes.mp4` | Practice quizzes |",
                "",
                f"- **Format:** MP4, H.264, {PREVIEW_W}×{PREVIEW_H}, {DURATION_SEC}s, no audio",
                "- **Note:** These are Ken Burns–style clips from marketing screenshots. For live UI motion,",
                "  replace with QuickTime/simulator screen recordings (15–30s) and re-encode to the same size.",
                "",
                "Generated by `python scripts/generate-app-store-previews.py`.",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Wrote {readme}")


if __name__ == "__main__":
    main()
